"""add email priority_score

Revision ID: 4a4ebbc056da
Revises: bc35f2ecace3
Create Date: 2026-06-10 11:07:01.286284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4ebbc056da'
down_revision: Union[str, None] = 'bc35f2ecace3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "emails",
        sa.Column("priority_score", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_emails_priority_score", "emails", ["priority_score"], unique=False)
    op.alter_column("emails", "priority_score", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emails_priority_score', table_name='emails')
    op.drop_column('emails', 'priority_score')
    # ### end Alembic commands ###
