"""add core crm models

Revision ID: bd19c5174ec7
Revises: 
Create Date: 2026-06-10 09:52:31.146338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd19c5174ec7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('VIP', 'Blocked', 'Active', 'Churned', name='contact_status', native_enum=False), nullable=False),
    sa.Column('account_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('churn_risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_contacts_status', 'contacts', ['status'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('Open', 'Resolved', 'Escalated', 'Ignored', name='thread_status', native_enum=False), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('ix_threads_last_updated_at', 'threads', ['last_updated_at'], unique=False)
    op.create_index('ix_threads_sender_email', 'threads', ['sender_email'], unique=False)
    op.create_index('ix_threads_status', 'threads', ['status'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('urgency', sa.String(length=32), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('Received', 'Processing', 'Replied', 'Escalated', 'Ignored', name='email_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index('ix_emails_sender', 'emails', ['sender'], unique=False)
    op.create_index('ix_emails_sender_timestamp', 'emails', ['sender', 'timestamp'], unique=False)
    op.create_index('ix_emails_status', 'emails', ['status'], unique=False)
    op.create_index('ix_emails_thread_id', 'emails', ['thread_id'], unique=False)
    op.create_index('ix_emails_timestamp', 'emails', ['timestamp'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('agent_reasoning_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_content', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_actions_email_id', 'actions', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actions_email_id', table_name='actions')
    op.drop_table('actions')
    op.drop_index('ix_emails_timestamp', table_name='emails')
    op.drop_index('ix_emails_thread_id', table_name='emails')
    op.drop_index('ix_emails_status', table_name='emails')
    op.drop_index('ix_emails_sender_timestamp', table_name='emails')
    op.drop_index('ix_emails_sender', table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_threads_status', table_name='threads')
    op.drop_index('ix_threads_sender_email', table_name='threads')
    op.drop_index('ix_threads_last_updated_at', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_contacts_status', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
